const goods = [
  {
    "id": "tn5001",
    "img": "./images/catalog/tn/a5/tn5001.jpg",
    "article": "ТН5001",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5002",
    "img": "./images/catalog/tn/a5/tn5002.jpg",
    "article": "ТН5002",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5003",
    "img": "./images/catalog/tn/a5/tn5003.jpg",
    "article": "ТН5003",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5004",
    "img": "./images/catalog/tn/a5/tn5004.jpg",
    "article": "ТН5004",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5005",
    "img": "./images/catalog/tn/a5/tn5005.jpg",
    "article": "ТН5005",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5006",
    "img": "./images/catalog/tn/a5/tn5006.jpg",
    "article": "ТН5006",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn5007",
    "img": "./images/catalog/tn/a5/tn5007.jpg",
    "article": "ТН5007",
    "type": "tnA5",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn4001",
    "img": "./images/catalog/tn/a4/tn4001.JPG",
    "article": "ТН4001",
    "type": "tnA4",
    "quantityBeads": 5,
    "quantityHalfBeads": 0,
    "quantityLuxe": 4,
    "quantitySHS": 5,
    "sketch": ""
  },
  {
    "id": "tn4002",
    "img": "./images/catalog/tn/a4/tn4002.JPG",
    "article": "ТН4002",
    "type": "tnA4",
    "quantityBeads": 12,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4003",
    "img": "./images/catalog/tn/a4/tn4003.JPG",
    "article": "ТН4003",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4,
    "sketch": "./images/catalog/tn/a4/sketch/sketch_tn4003.jpg"
  },
  {
    "id": "tn4004",
    "img": "./images/catalog/tn/a4/tn4004.JPG",
    "article": "ТН4004",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tn4005",
    "img": "./images/catalog/tn/a4/tn4005.JPG",
    "article": "ТН4005",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tn4006",
    "img": "./images/catalog/tn/a4/tn4006.JPG",
    "article": "ТН4006",
    "type": "tnA4",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn4007",
    "img": "./images/catalog/tn/a4/tn4007.JPG",
    "article": "ТН4007",
    "type": "tnA4",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn4008",
    "img": "./images/catalog/tn/a4/tn4008.jpg",
    "article": "ТН4008",
    "type": "tnA4",
    "quantityBeads": 18,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn4009",
    "img": "./images/catalog/tn/a4/tn4009.jpg",
    "article": "ТН4009",
    "type": "tnA4",
    "quantityBeads": 21,
    "quantityHalfBeads": 7,
    "quantityLuxe": 0,
    "quantitySHS": 28
  },
  {
    "id": "tn4010",
    "img": "./images/catalog/tn/a4/tn4010.jpg",
    "article": "ТН4010",
    "type": "tnA4",
    "quantityBeads": 18,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn4011",
    "img": "./images/catalog/tn/a4/tn4011.JPG",
    "article": "ТН4011",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn4012",
    "img": "./images/catalog/tn/a4/tn4012.JPG",
    "article": "ТН4012",
    "type": "tnA4",
    "quantityBeads": 17,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn4013",
    "img": "./images/catalog/tn/a4/tn4013.JPG",
    "article": "ТН4013",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4014",
    "img": "./images/catalog/tn/a4/tn4014.JPG",
    "article": "ТН4014",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4015",
    "img": "./images/catalog/tn/a4/tn4015.jpg",
    "article": "ТН4015",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4016",
    "img": "./images/catalog/tn/a4/tn4016.JPG",
    "article": "ТН4016",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 15
  },
  {
    "id": "tn4017",
    "img": "./images/catalog/tn/a4/tn4017.JPG",
    "article": "ТН4017",
    "type": "tnA4",
    "quantityBeads": 3,
    "quantityHalfBeads": 0,
    "quantityLuxe": 3,
    "quantitySHS": 4
  },
  {
    "id": "tn4018",
    "img": "./images/catalog/tn/a4/tn4018.JPG",
    "article": "ТН4018",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 5,
    "quantitySHS": 3
  },
  {
    "id": "tn4019",
    "img": "./images/catalog/tn/a4/tn4019.jpg",
    "article": "ТН4019",
    "type": "tnA4",
    "quantityBeads": 3,
    "quantityHalfBeads": 0,
    "quantityLuxe": 3,
    "quantitySHS": 4
  },
  {
    "id": "tn4020",
    "img": "./images/catalog/tn/a4/tn4020.jpg",
    "article": "ТН4020",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 7,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn4021",
    "img": "./images/catalog/tn/a4/tn4021.jpg",
    "article": "ТН4021",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 6
  },
  {
    "id": "tn4022",
    "img": "./images/catalog/tn/a4/tn4022.jpg",
    "article": "ТН4022",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 6
  },
  {
    "id": "tn4023",
    "img": "./images/catalog/tn/a4/tn4023.JPG",
    "article": "ТН4023",
    "type": "tnA4",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 6
  },
  {
    "id": "tn4024",
    "img": "./images/catalog/tn/a4/tn4024.JPG",
    "article": "ТН4024",
    "type": "tnA4",
    "quantityBeads": 3,
    "quantityHalfBeads": 0,
    "quantityLuxe": 3,
    "quantitySHS": 4
  },
  {
    "id": "tn4025",
    "img": "./images/catalog/tn/a4/tn4025.JPG",
    "article": "ТН4025",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 9,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn4026",
    "img": "./images/catalog/tn/a4/tn4026.JPG",
    "article": "ТН4026",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn4027",
    "img": "./images/catalog/tn/a4/tn4027.JPG",
    "article": "ТН4027",
    "type": "tnA4",
    "quantityBeads": 11,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 10
  },
  {
    "id": "tn4028",
    "img": "./images/catalog/tn/a4/tn4028.JPG",
    "article": "ТН4028",
    "type": "tnA4",
    "quantityBeads": 21,
    "quantityHalfBeads": 6,
    "quantityLuxe": 0,
    "quantitySHS": 27
  },
  {
    "id": "tn4029",
    "img": "./images/catalog/tn/a4/tn4029.JPG",
    "article": "ТН4029",
    "type": "tnA4",
    "quantityBeads": 9,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn4030",
    "img": "./images/catalog/tn/a4/tn4030.jpg",
    "article": "ТН4030",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn4031",
    "img": "./images/catalog/tn/a4/tn4031.JPG",
    "article": "ТН4031",
    "type": "tnA4",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn4032",
    "img": "./images/catalog/tn/a4/tn4032.JPG",
    "article": "ТН4032",
    "type": "tnA4",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn4033",
    "img": "./images/catalog/tn/a4/tn4033.JPG",
    "article": "ТН4033",
    "type": "tnA4",
    "quantityBeads": 17,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn4034",
    "img": "./images/catalog/tn/a4/tn4034.JPG",
    "article": "ТН4034",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 5,
    "quantityLuxe": 0,
    "quantitySHS": 17
  },
  {
    "id": "tn4035",
    "img": "./images/catalog/tn/a4/tn4035.jpg",
    "article": "ТН4035",
    "type": "tnA4",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tn4036",
    "img": "./images/catalog/tn/a4/tn4036.JPG",
    "article": "ТН4036",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tn4037",
    "img": "./images/catalog/tn/a4/tn4037.JPG",
    "article": "ТН4037",
    "type": "tnA4",
    "quantityBeads": 11,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4038",
    "img": "./images/catalog/tn/a4/tn4038.JPG",
    "article": "ТН4038",
    "type": "tnA4",
    "quantityBeads": 17,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 18,
    "sketch": "./images/catalog/tn/a4/sketch/sketch_tn4038.jpg"
  },
  {
    "id": "tn4039",
    "img": "./images/catalog/tn/a4/tn4039.jpg",
    "article": "ТН4039",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4040",
    "img": "./images/catalog/tn/a4/tn4040.JPG",
    "article": "ТН4040",
    "type": "tnA4",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7,
    "sketch": "./images/catalog/tn/a4/sketch/sketch_tn4040.jpg"
  },
  {
    "id": "tn4041",
    "img": "./images/catalog/tn/a4/tn4041.JPG",
    "article": "ТН4041",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 2,
    "quantityLuxe": 6,
    "quantitySHS": 6
  },
  {
    "id": "tn4042",
    "img": "./images/catalog/tn/a4/tn4042.JPG",
    "article": "ТН4042",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn4044",
    "img": "./images/catalog/tn/a4/tn4044.jpg",
    "article": "ТН4044",
    "type": "tnA4",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn4045",
    "img": "./images/catalog/tn/a4/tn4045.jpg",
    "article": "ТН4045",
    "type": "tnA4",
    "quantityBeads": 17,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 16
  },
  {
    "id": "tn4046",
    "img": "./images/catalog/tn/a4/tn4046.jpg",
    "article": "ТН4046",
    "type": "tnA4",
    "quantityBeads": 14,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 13
  },
  {
    "id": "tn4047",
    "img": "./images/catalog/tn/a4/tn4047.jpg",
    "article": "ТН4047",
    "type": "tnA4",
    "quantityBeads": 14,
    "quantityHalfBeads": 5,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn4048",
    "img": "./images/catalog/tn/a4/tn4048.jpg",
    "article": "ТН4048",
    "type": "tnA4",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 6
  },
  {
    "id": "tn4049+",
    "img": "./images/catalog/tn/a4/tn4049plus.jpg",
    "article": "ТН4049+",
    "type": "tnA4plus",
    "quantityBeads": 8,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4050+",
    "img": "./images/catalog/tn/a4/tn4050plus.jpg",
    "article": "ТН4050+",
    "type": "tnA4plus",
    "quantityBeads": 7,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4051",
    "img": "./images/catalog/tn/a4/tn4051.jpg",
    "article": "ТН4051",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 13
  },
  {
    "id": "tn4052",
    "img": "./images/catalog/tn/a4/tn4052.jpg",
    "article": "ТН4052",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 6,
    "quantityLuxe": 0,
    "quantitySHS": 20
  },
  {
    "id": "tn4053",
    "img": "./images/catalog/tn/a4/tn4053.jpg",
    "article": "ТН4053",
    "type": "tnA4",
    "quantityBeads": 17,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 20
  },
  {
    "id": "tn4055",
    "img": "./images/catalog/tn/a4/tn4055.jpg",
    "article": "ТН4055",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 15
  },
  {
    "id": "tn4056",
    "img": "./images/catalog/tn/a4/tn4056.jpg",
    "article": "ТН4056",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 6,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn4057",
    "img": "./images/catalog/tn/a4/tn4057.jpg",
    "article": "ТН4057",
    "type": "tnA4",
    "quantityBeads": 14,
    "quantityHalfBeads": 5,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn4057a",
    "img": "./images/catalog/tn/a4/tn4057a.jpg",
    "article": "ТН4057А",
    "type": "tnA4",
    "quantityBeads": 14,
    "quantityHalfBeads": 5,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn4058",
    "img": "./images/catalog/tn/a4/tn4058.jpg",
    "article": "ТН4058",
    "type": "tnA4",
    "quantityBeads": 15,
    "quantityHalfBeads": 6,
    "quantityLuxe": 0,
    "quantitySHS": 20
  },
  {
    "id": "tn4059",
    "img": "./images/catalog/tn/a4/tn4059.jpg",
    "article": "ТН4059",
    "type": "tnA4",
    "quantityBeads": 20,
    "quantityHalfBeads": 13,
    "quantityLuxe": 0,
    "quantitySHS": 33
  },
  {
    "id": "tn4060",
    "img": "./images/catalog/tn/a4/tn4060.jpg",
    "article": "ТН4060",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn4060a",
    "img": "./images/catalog/tn/a4/tn4060a.jpg",
    "article": "ТН4060А",
    "type": "tnA4",
    "quantityBeads": 7,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn4061",
    "img": "./images/catalog/tn/a4/tn4061.jpg",
    "article": "ТН4061",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tn4063",
    "img": "./images/catalog/tn/a4/tn4063.jpg",
    "article": "ТН4063",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn4064",
    "img": "./images/catalog/tn/a4/tn4064.jpg",
    "article": "ТН4064",
    "type": "tnA4",
    "quantityBeads": 13,
    "quantityHalfBeads": 10,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn4065",
    "img": "./images/catalog/tn/a4/tn4065.jpg",
    "article": "ТН4065",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4066",
    "img": "./images/catalog/tn/a4/tn4066.jpg",
    "article": "ТН4066",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4067",
    "img": "./images/catalog/tn/a4/tn4067.jpg",
    "article": "ТН4067",
    "type": "tnA4",
    "quantityBeads": 8,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn4068",
    "img": "./images/catalog/tn/a4/tn4068.jpg",
    "article": "ТН4068",
    "type": "tnA4",
    "quantityBeads": 6,
    "quantityHalfBeads": 0,
    "quantityLuxe": 2,
    "quantitySHS": 5
  },
  {
    "id": "tn4069",
    "img": "./images/catalog/tn/a4/tn4069.jpg",
    "article": "ТН4069",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 5,
    "quantitySHS": 4
  },
  {
    "id": "tn4070",
    "img": "./images/catalog/tn/a4/tn4070.jpg",
    "article": "ТН4070",
    "type": "tnA4",
    "quantityBeads": 2,
    "quantityHalfBeads": 0,
    "quantityLuxe": 4,
    "quantitySHS": 4
  },
  {
    "id": "tn4071",
    "img": "./images/catalog/tn/a4/tn4071.jpg",
    "article": "ТН4071",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 4,
    "quantitySHS": 3
  },
  {
    "id": "tn4072",
    "img": "./images/catalog/tn/a4/tn4072.jpg",
    "article": "ТН4072",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 4,
    "quantitySHS": 3
  },
  {
    "id": "tn4072",
    "img": "./images/catalog/tn/a4/tn4072black.jpg",
    "article": "ТН4072",
    "type": "tnA4",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 4,
    "quantitySHS": 3
  },
  {
    "id": "tn4073",
    "img": "./images/catalog/tn/a4/tn4073.jpg",
    "article": "ТН4073",
    "type": "tnA4",
    "quantityBeads": 19,
    "quantityHalfBeads": 6,
    "quantityLuxe": 0,
    "quantitySHS": 23
  },
  {
    "id": "tn3001m",
    "img": "./images/catalog/tn/a3/tn3001m.jpg",
    "article": "ТН3001",
    "type": "tnA3",
    "quantityBeads": 13,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  }
  ,
  {
    "id": "tn3002",
    "img": "./images/catalog/tn/a3/tn3002.jpg",
    "article": "ТН3002",
    "type": "tnA3",
    "quantityBeads": 17,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn3002",
    "img": "./images/catalog/tn/a3/tn3002black.jpg",
    "article": "ТН3002",
    "type": "tnA3",
    "quantityBeads": 17,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn3003",
    "img": "./images/catalog/tn/a3/tn3003.JPG",
    "article": "ТН3003",
    "type": "tnA3",
    "quantityBeads": 14,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn3004",
    "img": "./images/catalog/tn/a3/tn3004.JPG",
    "article": "ТН3004",
    "type": "tnA3",
    "quantityBeads": 14,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn3005",
    "img": "./images/catalog/tn/a3/tn3005.jpg",
    "article": "ТН3005",
    "type": "tnA3",
    "quantityBeads": 14,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn3006",
    "img": "./images/catalog/tn/a3/tn3006.JPG",
    "article": "ТН3006",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3006",
    "img": "./images/catalog/tn/a3/tn3006black.jpg",
    "article": "ТН3006",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3007",
    "img": "./images/catalog/tn/a3/tn3007.JPG",
    "article": "ТН3007",
    "type": "tnA3",
    "quantityBeads": 14,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9
  },
  {
    "id": "tn3008",
    "img": "./images/catalog/tn/a3/tn3008.JPG",
    "article": "ТН3008",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3008",
    "img": "./images/catalog/tn/a3/tn3008black.jpg",
    "article": "ТН3008",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3009",
    "img": "./images/catalog/tn/a3/tn3009.JPG",
    "article": "ТН3009",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3010",
    "img": "./images/catalog/tn/a3/tn3010.JPG",
    "article": "ТН3010",
    "type": "tnA3",
    "quantityBeads": 5,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 3
  },
  {
    "id": "tn3010black",
    "img": "./images/catalog/tn/a3/tn3010black.JPG",
    "article": "ТН3010",
    "type": "tnA3",
    "quantityBeads": 5,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 3
  },
  {
    "id": "tn3010blue",
    "img": "./images/catalog/tn/a3/tn3010blue.JPG",
    "article": "ТН3010",
    "type": "tnA3",
    "quantityBeads": 5,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 3
  },
  {
    "id": "tn3010green",
    "img": "./images/catalog/tn/a3/tn3010green.JPG",
    "article": "ТН3010",
    "type": "tnA3",
    "quantityBeads": 5,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 3
  },
  {
    "id": "tn3011",
    "img": "./images/catalog/tn/a3/tn3011.jpg",
    "article": "ТН3011",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3011gray",
    "img": "./images/catalog/tn/a3/tn3011gray.JPG",
    "article": "ТН3011",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3012",
    "img": "./images/catalog/tn/a3/tn3012.jpg",
    "article": "ТН3012",
    "type": "tnA3",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3012.jpg"
  },
  {
    "id": "tn3013",
    "img": "./images/catalog/tn/a3/tn3013.jpg",
    "article": "ТН3013",
    "type": "tnA3",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn3013black",
    "img": "./images/catalog/tn/a3/tn3013black.jpg",
    "article": "ТН3013",
    "type": "tnA3",
    "quantityBeads": 9,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5
  },
  {
    "id": "tn3014",
    "img": "./images/catalog/tn/a3/tn3014.jpg",
    "article": "ТН3014",
    "type": "tnA3",
    "quantityBeads": 22,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 15
  },
  {
    "id": "tn3014",
    "img": "./images/catalog/tn/a3/tn3014black.jpg",
    "article": "ТН3014",
    "type": "tnA3",
    "quantityBeads": 22,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 15
  },
  {
    "id": "tn3015",
    "img": "./images/catalog/tn/a3/tn3015.jpg",
    "article": "ТН3015",
    "type": "tnA3",
    "quantityBeads": 24,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn3015",
    "img": "./images/catalog/tn/a3/tn3015black.jpg",
    "article": "ТН3015",
    "type": "tnA3",
    "quantityBeads": 24,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn3016",
    "img": "./images/catalog/tn/a3/tn3016.jpg",
    "article": "ТН3016",
    "type": "tnA3",
    "quantityBeads": 17,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 17
  },
  {
    "id": "tn3016",
    "img": "./images/catalog/tn/a3/tn3016black.jpg",
    "article": "ТН3016",
    "type": "tnA3",
    "quantityBeads": 17,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 17
  },
  {
    "id": "tn3017",
    "img": "./images/catalog/tn/a3/tn3017.JPG",
    "article": "ТН3017",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3017",
    "img": "./images/catalog/tn/a3/tn3017black.jpg",
    "article": "ТН3017",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3018",
    "img": "./images/catalog/tn/a3/tn3018.JPG",
    "article": "ТН3018",
    "type": "tnA3",
    "quantityBeads": 22,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn3018",
    "img": "./images/catalog/tn/a3/tn3018black.jpg",
    "article": "ТН3018",
    "type": "tnA3",
    "quantityBeads": 22,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 19
  },
  {
    "id": "tn3019",
    "img": "./images/catalog/tn/a3/tn3019.JPG",
    "article": "ТН3019",
    "type": "tnA3",
    "quantityBeads": 17,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn3020",
    "img": "./images/catalog/tn/a3/tn3020.jpg",
    "article": "ТН3020",
    "type": "tnA3",
    "quantityBeads": 18,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 12
  },
  {
    "id": "tn3021",
    "img": "./images/catalog/tn/a3/tn3021.JPG",
    "article": "ТН3021",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3022",
    "img": "./images/catalog/tn/a3/tn3022.JPG",
    "article": "ТН3022",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3022.jpg"
  },
  {
    "id": "tn3023",
    "img": "./images/catalog/tn/a3/tn3023.JPG",
    "article": "ТН3023",
    "type": "tnA3",
    "quantityBeads": 24,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 17
  },
  {
    "id": "tn3023",
    "img": "./images/catalog/tn/a3/tn3023black.jpg",
    "article": "ТН3023",
    "type": "tnA3",
    "quantityBeads": 24,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 17
  },
  {
    "id": "tn3024",
    "img": "./images/catalog/tn/a3/tn3024.JPG",
    "article": "ТН3024",
    "type": "tnA3",
    "quantityBeads": 16,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 11,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3024.jpg"
  },
  {
    "id": "tn3025",
    "img": "./images/catalog/tn/a3/tn3025.JPG",
    "article": "ТН3025",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3026",
    "img": "./images/catalog/tn/a3/tn3026.jpg",
    "article": "ТН3026",
    "type": "tnA3",
    "quantityBeads": 19,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 18,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3026.jpg"
  },
  {
    "id": "tn3027",
    "img": "./images/catalog/tn/a3/tn3027.jpg",
    "article": "ТН3027",
    "type": "tnA3",
    "quantityBeads": 25,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 20
  },
  {
    "id": "tn3027black",
    "img": "./images/catalog/tn/a3/tn3027black.jpg",
    "article": "ТН3027",
    "type": "tnA3",
    "quantityBeads": 25,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 20
  },
  {
    "id": "tn3027plus",
    "img": "./images/catalog/tn/a3/tn3027plus.jpg",
    "article": "ТН3027+",
    "type": "tnA3plus",
    "quantityBeads": 28,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 21
  },
  {
    "id": "tn3028",
    "img": "./images/catalog/tn/a3/tn3028.jpg",
    "article": "ТН3028",
    "type": "tnA3",
    "quantityBeads": 19,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 14,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3028.jpg"
  },
  {
    "id": "tn3029",
    "img": "./images/catalog/tn/a3/tn3029.jpg",
    "article": "ТН3029",
    "type": "tnA3",
    "quantityBeads": 19,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 15,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3029.jpg"
  },
  {
    "id": "tn3030",
    "img": "./images/catalog/tn/a3/tn3030.jpg",
    "article": "ТН3030",
    "type": "tnA3",
    "quantityBeads": 26,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 21,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3030.jpg"
  },
  {
    "id": "tn3031",
    "img": "./images/catalog/tn/a3/tn3031.jpg",
    "article": "ТН3031",
    "type": "tnA3",
    "quantityBeads": 14,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 10
  },
  {
    "id": "tn3032",
    "img": "./images/catalog/tn/a3/tn3032.jpg",
    "article": "ТН3032",
    "type": "tnA3",
    "quantityBeads": 15,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 11
  },
  {
    "id": "tn3033",
    "img": "./images/catalog/tn/a3/tn3033.jpg",
    "article": "ТН3033",
    "type": "tnA3",
    "quantityBeads": 20,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 14,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3033.jpg"
  },
  {
    "id": "tn3034",
    "img": "./images/catalog/tn/a3/tn3034.jpg",
    "article": "ТН3034",
    "type": "tnA3",
    "quantityBeads": 13,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3034.jpg"
  },
  {
    "id": "tn3035",
    "img": "./images/catalog/tn/a3/tn3035.jpg",
    "article": "ТН3035",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3035.jpg"
  },
  {
    "id": "tn30036",
    "img": "./images/catalog/tn/a3/tn3036.jpg",
    "article": "ТН3036",
    "type": "tnA3",
    "quantityBeads": 16,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 10
  },
  {
    "id": "tn3037",
    "img": "./images/catalog/tn/a3/tn3037.jpg",
    "article": "ТН3037",
    "type": "tnA3",
    "quantityBeads": 9,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3038",
    "img": "./images/catalog/tn/a3/tn3038.jpg",
    "article": "ТН3038",
    "type": "tnA3",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 2,
    "quantitySHS": 5
  },
  {
    "id": "tn3039",
    "img": "./images/catalog/tn/a3/tn3039.jpg",
    "article": "ТН3039",
    "type": "tnA3",
    "quantityBeads": 16,
    "quantityHalfBeads": 1,
    "quantityLuxe": 0,
    "quantitySHS": 10
  },
  {
    "id": "tn3040",
    "img": "./images/catalog/tn/a3/tn3040.jpg",
    "article": "ТН3040",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3041",
    "img": "./images/catalog/tn/a3/tn3041.jpg",
    "article": "ТН3041",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3041.jpg"
  },
  {
    "id": "tn3042",
    "img": "./images/catalog/tn/a3/tn3042.jpg",
    "article": "ТН3042",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3043",
    "img": "./images/catalog/tn/a3/tn3043.jpg",
    "article": "ТН3043",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0
  },
  {
    "id": "tn3043A",
    "img": "./images/catalog/tn/a3/tn3043A.jpg",
    "article": "ТН3043А",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3044",
    "img": "./images/catalog/tn/a3/tn3044.jpg",
    "article": "ТН3044",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3044.jpg"
  },
  {
    "id": "tn3045",
    "img": "./images/catalog/tn/a3/tn3045.jpg",
    "article": "ТН3045",
    "type": "tnA3",
    "quantityBeads": 12,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3046",
    "img": "./images/catalog/tn/a3/tn3046.jpg",
    "article": "ТН3046",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 7,
    "quantitySHS": 4
  },
  {
    "id": "tn3046",
    "img": "./images/catalog/tn/a3/tn3046black.jpg",
    "article": "ТН3046",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 7,
    "quantitySHS": 4
  },
  {
    "id": "tn3047",
    "img": "./images/catalog/tn/a3/tn3047.jpg",
    "article": "ТН3047",
    "type": "tnA3",
    "quantityBeads": 9,
    "quantityHalfBeads": 2,
    "quantityLuxe": 0,
    "quantitySHS": 8
  },
  {
    "id": "tn3048",
    "img": "./images/catalog/tn/a3/tn3048.jpg",
    "article": "ТН3048",
    "type": "tnA3",
    "quantityBeads": 21,
    "quantityHalfBeads": 3,
    "quantityLuxe": 0,
    "quantitySHS": 23,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3048.jpg"
  },
  {
    "id": "tn3049",
    "img": "./images/catalog/tn/a3/tn3049.jpg",
    "article": "ТН3049",
    "type": "tnA3",
    "quantityBeads": 11,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 7
  },
  {
    "id": "tn3050",
    "img": "./images/catalog/tn/a3/tn3050.jpg",
    "article": "ТН3050",
    "type": "tnA3",
    "quantityBeads": 18,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 16
  },
  {
    "id": "tn3050",
    "img": "./images/catalog/tn/a3/tn3050black.jpg",
    "article": "ТН3050",
    "type": "tnA3",
    "quantityBeads": 18,
    "quantityHalfBeads": 4,
    "quantityLuxe": 0,
    "quantitySHS": 16
  },
  {
    "id": "tn3051",
    "img": "./images/catalog/tn/a3/tn3051.jpg",
    "article": "ТН3051",
    "type": "tnA3",
    "quantityBeads": 18,
    "quantityHalfBeads": 5,
    "quantityLuxe": 0,
    "quantitySHS": 18
  },
  {
    "id": "tn3052",
    "img": "./images/catalog/tn/a3/tn3052.jpg",
    "article": "ТН3052",
    "type": "tnA3",
    "quantityBeads": 26,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 22
  },
  {
    "id": "tn3052",
    "img": "./images/catalog/tn/a3/tn3052black.jpg",
    "article": "ТН3052",
    "type": "tnA3",
    "quantityBeads": 26,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 22
  },
  {
    "id": "tn3053",
    "img": "./images/catalog/tn/a3/tn3053.jpg",
    "article": "ТН3053",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3053.jpg"
  },
  {
    "id": "tn3054",
    "img": "./images/catalog/tn/a3/tn3054.jpg",
    "article": "ТН3054",
    "type": "tnA3",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 0,
    "sketch": "./images/catalog/tn/a3/sketch/sketch_tn3054.jpg"
  },
  {
    "id": "tnp001",
    "img": "./images/catalog/tn/tapestry/tnp001.jpg",
    "article": "ТНП001",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tnp002",
    "img": "./images/catalog/tn/tapestry/tnp002.jpg",
    "article": "ТНП002",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 4
  },
  {
    "id": "tnp003",
    "img": "./images/catalog/tn/tapestry/tnp003.jpg",
    "article": "ТНП003",
    "type": "tnP2060",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 7,
    "quantitySHS": 4
  },
  {
    "id": "tnp004",
    "img": "./images/catalog/tn/tapestry/tnp004.jpg",
    "article": "ТНП004",
    "type": "tnP2060",
    "quantityBeads": 0,
    "quantityHalfBeads": 0,
    "quantityLuxe": 7,
    "quantitySHS": 4
  },
  {
    "id": "tnp005",
    "img": "./images/catalog/tn/tapestry/tnp005.jpg",
    "article": "ТНП005",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5,
    "sketch": "./images/catalog/tn/tapestry/sketch/sketch_tnp005.jpg"
  },
  {
    "id": "tnp006",
    "img": "./images/catalog/tn/tapestry/tnp006.jpg",
    "article": "ТНП006",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 3,
    "quantitySHS": 6,
  },
  {
    "id": "tnp007",
    "img": "./images/catalog/tn/tapestry/tnp007.jpg",
    "article": "ТНП007",
    "type": "tnP2060",
    "quantityBeads": 10,
    "quantityHalfBeads": 0,
    "quantityLuxe": 1,
    "quantitySHS": 7,
  },
  {
    "id": "tnp008",
    "img": "./images/catalog/tn/tapestry/tnp008.jpg",
    "article": "ТНП008",
    "type": "tnP2060",
    "quantityBeads": 15,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9,
  },
  {
    "id": "tnp008",
    "img": "./images/catalog/tn/tapestry/tnp008black.jpg",
    "article": "ТНП008",
    "type": "tnP2060",
    "quantityBeads": 15,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 9,
  },
  {
    "id": "tnp009",
    "img": "./images/catalog/tn/tapestry/tnp009.jpg",
    "article": "ТНП009",
    "type": "tnP2060",
    "quantityBeads": 24,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 20,
  },
  {
    "id": "tnp009",
    "img": "./images/catalog/tn/tapestry/tnp009black.jpg",
    "article": "ТНП009",
    "type": "tnP2060",
    "quantityBeads": 24,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 20,
  },
  {
    "id": "tnp010",
    "img": "./images/catalog/tn/tapestry/tnp010.jpg",
    "article": "ТНП010",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5,
  },
  {
    "id": "tnp010",
    "img": "./images/catalog/tn/tapestry/tnp010black.jpg",
    "article": "ТНП010",
    "type": "tnP2060",
    "quantityBeads": 7,
    "quantityHalfBeads": 0,
    "quantityLuxe": 0,
    "quantitySHS": 5,
  }
]

export {goods};